apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  labels:
    app.kubernetes.io/instance: chat-bot-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chat-bot-test
    app.kubernetes.io/part-of: chat-bot-test
  name: chat-bot-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: chat-bot-test
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: chat-bot-test
    spec:
      containers:
        - image: quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
          name: app-inference
          envFrom:
            - configMapRef:
                name: chat-bot-test-model-config
          ports:
            - containerPort: 8501
          securityContext:
            runAsNonRoot: true
