apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: chat-bot-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chat-bot-test
  name: chat-bot-test
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
  selector:
    app.kubernetes.io/instance: chat-bot-test
